### ISSUE TITLE
The spec does not deal with replaced elements like <select> which have textContent but no innerText

### ISSUE THREAD

**Issue by FremyCompany** [rocallahan/innerText-spec#1]
I think the spec needs to define why the following DIV has an empty textContent (more clearly if this is already covered)

```
<div>
    <select><option>X</option><option>Y</option><option>Z</option></select>
</div>
```

**Comment by FremyCompany** [comment]
Oh, that behavior seems to happen in Chrome only. I think this behavior makes sense, though, because the content or placeholder of an <input> element not propagated to innerText in all browsers. This may or may not be worth updating the spec though, let me know what you think.

**Comment by kangax** [comment]
Chrome and FF don't include `<select>` contents; IE and Edge do — http://kangax.github.io/jstests/innerText/

**Comment by rocallahan** [comment]
The spec already defines that DIV to have empty innerText. Descendant nodes of `<select>` are not rendered by CSS, strictly speaking, and therefore have no CSS boxes for the purposes of the spec, so if you apply the spec algorithm it will return the empty string.
