### ISSUE TITLE
maybe add some tests for successive <pre> items

### ISSUE THREAD

**Issue by PerBothner** [rocallahan/innerText-spec#4]
Maybe you could add a test for successive &lt;pre> items? E.g:

```
<pre>line1</pre><pre>line2</pre>
```

The reason is that while Firefox (46.0a1) gets this correct (IMO i.e. a single newline between the texts) when it comes to innerText, it puts _two_ newlines between them when doing a Copy. So adding a test would I think help clarify what the "correct" behavior is

**Comment by zcorpan** [comment]
Test added to web-platform-tests; this can be closed.
